apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orchestrator
  labels:
    {{- include "lvca.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: {{ .Values.orchestrator.service.type }}
  ports:
    - port: {{ .Values.orchestrator.service.port }}
      targetPort: {{ .Values.orchestrator.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
